# Generated by Django 6.0.5 on 2026-05-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
