# Generated by Django 6.0.5 on 2026-05-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_group_groupmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="code_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_public",
            field=models.BooleanField(default=True, help_text="is email public?"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location_private",
            field=models.BooleanField(default=True, help_text="Is location private?"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location_text",
            field=models.CharField(
                blank=True, help_text="Location (Tashkent, Uzbekistan)", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="streak_days",
            field=models.IntegerField(default=0, help_text="Streak Days (12)"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="success_rate",
            field=models.IntegerField(
                default=0, help_text="Success Rate Percentage (92%)"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_challenges",
            field=models.IntegerField(default=0, help_text="Number of Chaqiriqlar"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_level",
            field=models.IntegerField(default=1, help_text="User level 12"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_profession",
            field=models.CharField(
                blank=True, help_text="User profession (Programer)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="joined_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="UserChalanges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "location_url",
                    models.URLField(
                        blank=True,
                        help_text="Google Maps yoki havola linki",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_days", models.IntegerField(default=30)),
                ("days_completed", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challanges",
                        to="main.userprofile",
                    ),
                ),
            ],
        ),
    ]
